iam_role:
  Path: /
  RoleName: SageExec
  RoleId: AROAZ5TC43XQ62J53YTZI
  Arn: arn:aws:iam::682033470945:role/SageExec
  CreateDate: '2024-08-26T10:45:26+00:00'
  AssumeRolePolicyDocument:
    Version: '2012-10-17'
    Statement:
    - Sid: ''
      Effect: Allow
      Principal:
        Service: sagemaker.amazonaws.com
      Action: sts:AssumeRole
  Description: Allows SageMaker notebook instances, training jobs, and models to access
    S3, ECR, and CloudWatch on your behalf.
  MaxSessionDuration: 3600
  RoleLastUsed: {}
